// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  image_links: dynamic(() => import("./ImageLinks")),
  text_block: dynamic(() => import("./TextBlock")),
};
