// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordions: dynamic(() => import("./Accordions")),
  hero: dynamic(() => import("./Hero")),
  image_links: dynamic(() => import("./ImageLinks")),
  logos: dynamic(() => import("./Logos")),
  text_block: dynamic(() => import("./TextBlock")),
};
